version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=boaproddb
      - MYSQL_USER=system
      - MYSQL_PASSWORD=root123
    volumes:
      - /data/mysql
  demo-app:
    image: repo/kycprocess-compose-app
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
    ports:
      - 7080:6060
    volumes:
      - /data/compose-app